security:
    resource: "@AppBundle/Controller/SecurityController.php"
    type:     annotation
wiki:
    resource: "@AppBundle/Controller/WikiController.php"
    type:     annotation
user:
    resource: "@AppBundle/Controller/UserController.php"
    type:     annotation
page:
    resource: "@AppBundle/Controller/PageController.php"
    type:     annotation
