# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    markdown:
        class: AppBundle\Service\MarkdownService
    slug:
        class: AppBundle\Service\SlugService
        arguments: [%app.slug.character%]
    app.repository:
        class: AppBundle\Service\RepositoryService
        arguments: ['%app.wiki.root%']
    app.twig_extension:
        class: AppBundle\Twig\AppExtension
        arguments: ['@markdown']
        public: false
        tags:
            - { name: twig.extension }
