# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    markdown:
        class: AppBundle\Service\MarkdownService
    slug:
        class: AppBundle\Service\SlugService
        arguments: [%app.slug.character%]
    app.git_user_provider:
        class: AppBundle\Security\User\GitUserProvider
        arguments: ['@app.repository', '%app.admin_repository%']
    app.git_user_factory:
        class: AppBundle\Security\User\GitUserFactory
        arguments: ['@=container']
    app.repository:
        class: AppBundle\Service\RepositoryService
        arguments: ['%app.wiki.root%', '%app.admin_repository%']
    app.twig_extension:
        class: AppBundle\Twig\AppExtension
        arguments: ['@markdown', '@slug']
        public: false
        tags:
            - { name: twig.extension }
    app.wiki_voter:
        class: AppBundle\Security\Authorization\Voter\WikiVoter
        arguments: ['@app.repository', '%app.admin_repository%', '%app.admin_group%']
        tags:
            - { name: security.voter }
        public: false
